roughike/BottomBar

bottom-bar/src/main/AndroidManifest.xml

The library project should not contain an `application` element as there is no application included. This causes issues with the manifest merger when using this library with an app that has an `app_name` defined in the `application` element.
The other workaround is to use `tools:replace="android:label"`.
```
Manifest merger failed : Attribute application@label value=(XYZ) from AndroidManifest.xml:31:9-35 is also present at [com.roughike:bottom-bar:1.1.7] AndroidManifest.xml:11:18-50 value=(@string/app_name).
Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:27:5-219:19 to override.
```

Removing application from the library manifest

---

app/src/main/java/com/example/bottombar/sample/MainActivity.java
bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java
bottom-bar/src/main/java/com/roughike/bottombar/OnMenuTabItemClickListener.java
bottom-bar/src/main/java/com/roughike/bottombar/OnMenuTabSelectedListener.java
bottom-bar/src/main/java/com/roughike/bottombar/OnTabItemClickListener.java
bottom-bar/src/main/java/com/roughike/bottombar/OnTabSelectedListener.java

First off, thank you for this amazing library and all the hard work that you have put in!
The [Material Behavior spec](https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-behavior) states the following:
* Tapping on the active action in the bottom navigation bar will navigate the user to the top of the view.
Currently, the listeners are only notified if `newPosition != mCurrentTabPosition` and so they are not notified if the user taps the active action. This PR makes a small change to notify the listeners in all cases

Interface to notify listeners when the current action is reselected

---

bottom-bar/src/main/java/com/roughike/bottombar/MiscUtils.java

Currently **MiscUtils.getColor** is only used in **BottomBar.init**
`mPrimaryColor = MiscUtils.getColor(getContext(), R.attr.colorPrimary);`
The hard coding '**R.attr.colorPrimary**' could be safely removed. :)

remove the hard coding primary-color here

---

bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java

Fixes issue #214.
In `selectTabAtPosition`, `shiftingMagic()` was always being called with `false` instead of using `animate` parameter

Fix animation bug when programmatically selecting tab (issue #214)

---

README.md
app/app.iml
app/src/main/java/com/example/bottombar/sample/MainActivity.java
bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java

In this PR, I deprecated the existing method that sets both the menu items from XML and the click listener at the same time. I think this is better for a number of reasons:
1. This allows the listener to be nulled out. This clears the path for creating a binding for the click listener that can be unsubscribed from, in the pattern of Jake Wharton's RxBinding library.
2. The API of BottomBar now more closely follows other widgets that inflate items from XML, such as the toolbar, where menu inflation and listener management are separate operations.

Break up setting of items from menu and setting of click listener

---

bottom-bar/src/main/java/com/roughike/bottombar/BottomBarBadge.java

When using badges, an extra FrameLayout is inserted as the container
for each tab. This container inherits the tag of the pre-badge tab view,
but the tag is not reset on the pre-badge tab view. This causes selection
and unselection of tabs to fail because findViewWithTag will erroneously
find the now obsolete tab views when searching for active tabs, resulting
in multiple tabs being visually selected when changing tabs.
By clearing the tag of the old (now inner) view when putting it in the new
tab container, we can ensure that findViewWithTag will only find relevant
views.
This fixes #266.

Fix selection/unselection when using badges

---

bottom-bar/src/main/java/com/roughike/bottombar/BottomBarBadge.java

Otherwise will trigger an infinite loop of layout re-drawing if a badge is present which a) is bad for performance and b) breaks interactions with other custom behaviors
You can see this by overriding requestLayout in BottomBar.java:
```
@Override
public void requestLayout() {
super.requestLayout();
}
```
You will observe this breakpoint is hit continually in the event that a badge is drawn on one of the tabs. 
This took me about 3 hrs to debug and I would suggest is a Very Serious regression. Thanks!

Only apply new layout params if they have actually changed.

---

bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java
bottom-bar/src/main/java/com/roughike/bottombar/BottomBarItemBase.java
bottom-bar/src/main/res/layout/bb_bottom_bar_item_fixed.xml
bottom-bar/src/main/res/layout/bb_bottom_bar_item_fixed_tablet.xml
bottom-bar/src/main/res/layout/bb_bottom_bar_item_shifting.xml

Minor changes to support vector drawables

Minor changes to support vector drawables

---

bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java

forceFixedMode() is no longer exist and will not work, however this is still reference in the console output when people trying to use force title in tab bar. This update the reference in the output with the new method name.

Update outdated method name in error output to help debugging

---

bottom-bar/src/main/java/com/roughike/bottombar/MiscUtils.java

Replacing the stock PopupMenu with the support one allows automatic support for vector drawable for API < 21.

Switch to support PopupMenu for vector drawables

---

bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java

When called with `0`, `setItems` throws an error, causing an `InflationException`.

Don't load tabs if no tab resource is set

---

bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java
bottom-bar/src/main/java/com/roughike/bottombar/MiscUtils.java

This resizes tabs according to the width of the parent view rather than the screen width. So for example, you can have a bottom tab bar on one side of a split view (master-detail), if you want.

tabs redraw width based on view not screen

---

app/src/main/java/com/example/bottombar/sample/ThreeTabsActivity.java
app/src/main/res/layout/activity_three_tabs.xml
bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java

The changes in the PR fix a couple of issues with regards to setting the tab items programmatically while setting up the layout in XML.
- It removes the requirement to have the tabs defined in the XML layout
- If the user sets the tab items programmatically, the previously rendered tabs are cleared before the new list is rendered.

Fixed setting items programatically

---

bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java
bottom-bar/src/main/java/com/roughike/bottombar/BottomBarTab.java
bottom-bar/src/main/res/values/attrs.xml

This allows the possibility of keeping the badges visible when the tab is selected
this is a nice feature that existed before 2.0 and is preventing us from updating to the latest version

Add ability to keep badges visible even when the tab is selected

---

bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java
bottom-bar/src/main/java/com/roughike/bottombar/MiscUtils.java

fixed faulty pixel to DP conversion, that caused first and last tab to go outside bounds of bar
fixed active tab width for active element in shifting mode

fix for calculating width of tabs

---

bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java
bottom-bar/src/main/java/com/roughike/bottombar/OnTabShouldSelectListener.java
bottom-bar/src/main/java/com/roughike/bottombar/TabOverrideListener.java

Adding a way to intercept tab selection.
**EDIT**
I've added an interface `OnTabShouldSelectListener` with a single method `boolean onTabShouldSelect(@IdRes int oldTabId, @IdRes int newTabId)`. The purpose of this is to be able to add logic to stop tab changes. There may be a better name for this interface and/or method. The `BottomBar` checks in `private void handleClick(View v)` for a non-null `onTabShouldSelectListener ` and calls out to it to see if it should proceed with the tab change. This technically intercepts both select and reselect. I could also break the interface into two different methods, or rename the interface to something more encompassing.
Our use case is that we want to warn the user of unsaved changes before they go (and then programmatically proceed with the tab …

Adding OnTabShouldSelectListener

---

bottom-bar/src/main/java/com/roughike/bottombar/BottomBarTab.java

- Setting the "selected" state to true when the tab is active, and false otherwise
- This allows the use of DrawableSelectors in case you need to change the drawable when tab selected

Allowing drawable selectors to change icon when tab is selected

---

bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java
bottom-bar/src/main/java/com/roughike/bottombar/MiscUtils.java
bottom-bar/src/main/res/layout-v21/bb_bottom_bar_item_container.xml
bottom-bar/src/main/res/layout/bb_bottom_bar_item_container.xml
bottom-bar/src/main/res/values/dimensions.xml

- Removing the view for API 21
- Adding a negative margin for API 20 or less so that the content is overlapped with the shadow
- Fix the annotation for the MiscUtils

Fix for shadow

---

bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java

- Setting the modified LayoutParams so that the views are changed

[Bug Fix] Tabs of incorrect size

---

bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java
bottom-bar/src/main/java/com/roughike/bottombar/BottomNavigationBehavior.java
bottom-bar/src/main/java/com/roughike/bottombar/ShySettings.java

This needs some input:
- Is the method naming on point? Could it be misinterpreted somehow?
- Do we want to support hide / show methods when NOT on shy mode? The layouts can be quite complex and I personally think hiding the regular (=not shy) BottomBars should probably be the user's job, as this is a regular view after all.

Show & Hide methods when on shy mode.

---

bottom-bar/src/main/java/com/roughike/bottombar/BottomBarTab.java

This is a fix for #708 
Replacing the faulty onAnimationEnd() listener by a postDelayed() call.

Fix wrong badge position in shifting mode (#708)

---

CHANGELOG.md
README.md
bottom-bar/build.gradle
bottom-bar/src/main/java/com/roughike/bottombar/BottomBar.java
bottom-bar/src/main/java/com/roughike/bottombar/BottomBarTab.java
bottom-bar/src/main/res/layout/bb_bottom_bar_item_container.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

As reported in #784, I updated `supportLibraryVersion` from `25.3.0` to `25.3.1`.
I used this local build with my project instead of release v2.3.1 and it builds correctly.
I run the `:bottom-bar` tests locally and all of them passed.

Bumped Support Library to 25.3.1
